"""Git agent.

Deliberately not an LLM agent: branch, commit and pull-request creation are
deterministic operations with real side effects, so they are plain code driven
by the workflow (section 49 - code enforces, prompts only guide).
"""

from __future__ import annotations

from pathlib import Path

from core.logging import get_logger
from graph.state import AgentState
from providers.scm.base import PullRequest, SourceControlProvider
from tools.git.commit import commit_all

log = get_logger(__name__)

MAX_SUBJECT = 72


def commit_message(state: AgentState) -> str:
    summary = (
        state.get("implementation_summary")
        or state.get("plan_summary")
        or state.get("issue", "agent change")
    ).strip().splitlines()[0]
    subject = summary if len(summary) <= MAX_SUBJECT else summary[: MAX_SUBJECT - 3] + "..."

    criteria = "\n".join(f"- {item}" for item in state.get("acceptance_criteria", []))
    files = "\n".join(f"- {path}" for path in state.get("modified_files", []))
    body = [
        "",
        f"Task: {state.get('task_id', '')}",
        f"Issue: {state.get('issue', '').strip()}",
        "",
        "Acceptance criteria:",
        criteria or "- (none recorded)",
        "",
        "Files changed:",
        files or "- (none recorded)",
        "",
        f"Tests: passed={state.get('tests_passed', 0)} failed={state.get('tests_failed', 0)}",
        f"Debug iterations: {state.get('iteration', 0)}",
        "",
        "Generated by the AI Software Engineering Agent. Requires human review before merge.",
    ]
    return subject + "\n" + "\n".join(body)


def pull_request_body(state: AgentState) -> str:
    sections = [
        f"**Task:** `{state.get('task_id', '')}`",
        "",
        "## Issue",
        state.get("issue", ""),
        "",
        "## What changed",
        state.get("implementation_summary") or state.get("plan_summary", ""),
        "",
        "## Acceptance criteria",
        "\n".join(f"- [ ] {item}" for item in state.get("acceptance_criteria", [])) or "- (none)",
        "",
        "## Files changed",
        "\n".join(f"- `{path}`" for path in state.get("modified_files", [])) or "- (none)",
        "",
        "## Verification",
        f"- Tests: passed={state.get('tests_passed', 0)}, failed={state.get('tests_failed', 0)}",
        f"- CI: {state.get('ci_status') or 'not run'}",
        f"- Risk: {state.get('risk_level', 'LOW')}",
        f"- Debug iterations: {state.get('iteration', 0)}",
        "",
        "## Policy",
        "\n".join(f"- {finding}" for finding in state.get("policy_findings", [])) or "- no findings",
        "",
        "---",
        "Opened by the AI Software Engineering Agent. A human must review and merge.",
    ]
    return "\n".join(sections)


async def commit_changes(state: AgentState, workspace_path: Path) -> str:
    sha = await commit_all(workspace_path, commit_message(state))
    log.info("git_agent.committed", task_id=state.get("task_id"), sha=sha)
    return sha


async def open_pull_request(
    state: AgentState, workspace_path: Path, provider: SourceControlProvider
) -> PullRequest:
    branch = state.get("git_branch", "")
    await provider.push_branch(workspace_path, branch)
    title = (
        state.get("implementation_summary")
        or state.get("plan_summary")
        or f"Agent change for {state.get('task_id', '')}"
    ).strip().splitlines()[0][:MAX_SUBJECT]
    return await provider.create_pull_request(
        branch=branch, title=title, body=pull_request_body(state)
    )
